
const prompts = [
  ["hi", "hey", "hello", "good morning", "good afternoon"],
  ["how are you", "how is life", "how are things"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  ["your name please", "your name", "may i know your name", "what is your name", "what call yourself"],
  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["bad", "bored", "tired"],
  ["help me", "tell me story", "tell me joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "good bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no","not sure","maybe","no thanks"],
  [""],
  ["haha","ha","lol","hehe","funny","joke"],
  ["ecommerce", "Define e-commerce", "Explain e-commerce"],
  ["How can I start selling online?", "What are the steps to begin online selling?", "Guide me in starting an online business"],
  ["What are the key components of a successful e-commerce website?", "List elements for a successful online store", "Define crucial parts of an e-commerce site"],
  ["How important is digital marketing in e-commerce?", "Explain the role of digital marketing in online selling", "Why is digital marketing crucial for e-commerce?"],
  ["What are some common challenges in e-commerce?", "List challenges faced by online sellers", "Explain obstacles in the e-commerce industry"],
  ["How can I optimize my product listings?", "What are strategies for effective product descriptions?", "Guide me in optimizing product listings for online sales"],
  ["What payment options should I offer in my online store?", "List secure payment methods for e-commerce", "Explain best practices for online payment processing"],
  ["How can I improve customer satisfaction in e-commerce?", "What strategies enhance customer experience online?", "Guide me in providing excellent customer service in my online business"],
  ["What is dropshipping?", "Explain the concept of dropshipping", "How does dropshipping work in e-commerce?"],
  ["What trends are shaping the future of e-commerce?", "List emerging trends in online selling", "Explain the future landscape of e-commerce"],
  ["How do I handle returns and refunds in e-commerce?", "What is the process for managing returns and refunds?", "Guide me in handling product returns for my online business"],
  ["What is the significance of customer reviews in e-commerce?", "Explain the importance of customer feedback in online selling", "Why are customer reviews crucial for e-commerce success?"],
  ["What role does social media play in e-commerce marketing?", "How can I leverage social media for online marketing?", "Explain the impact of social media on e-commerce promotion"],
  ["What is SEO, and how does it benefit e-commerce?", "Define SEO in the context of online selling", "How can I optimize my website for search engines in e-commerce?"],
  ["What are the considerations for setting shipping policies in e-commerce?", "Guide me in establishing effective shipping policies for my online store", "How should I determine shipping rates for my products?"],
  ["How can I protect customer data in my e-commerce business?", "What measures should I take to ensure data security in online transactions?", "Guide me in implementing data protection practices in e-commerce"],
  ["What is the role of AI in personalizing the e-commerce shopping experience?", "Explain how AI enhances personalization for online shoppers", "How can I incorporate AI for personalized recommendations in my online store?"],
  ["What are the advantages of selling on online marketplaces?", "Explain the benefits of listing products on online marketplaces", "Why should I consider selling on multiple online platforms?"],
  ["How can I build brand loyalty in e-commerce?", "What strategies enhance brand loyalty for online businesses?", "Guide me in fostering customer loyalty in my e-commerce store"],
  ["What are some effective strategies for reducing cart abandonment in e-commerce?", "How can I minimize cart abandonment in my online store?", "Guide me in implementing strategies to increase conversion rates in e-commerce"],
  ["what are the different types of amazon seller accounts in india?"],
  ["what documents do i need to open an amazon india seller account?"],
  ["what are the fees associated with selling on amazon india?"],
  ["what products can i sell on amazon india?"],
  ["how do i list my products on amazon india?"],
  ["how do i ship my products to amazon india customers?"],
  ["how can i promote my products on amazon india?"],
  ["how do i provide customer service on amazon india?"],
  ["what happens if i receive negative feedback?"],
  ["how can i grow my amazon india seller business?"],
  ["what are the benefits of selling on amazon india compared to other platforms?"],
  ["how can i ensure my product listings are optimized for indian search terms?"],
  ["what are the best practices for product pricing on amazon india?"],
  ["how can i manage my inventory effectively to avoid stockouts or overstocking?"],
  ["what are the different ways to offer customer support on amazon india?"],
  ["how can i use amazon india's promotional tools and events to boost sales?"],
  ["what are the legal and regulatory considerations for selling specific product categories on amazon india?"],
  ["how can i build a positive brand reputation on amazon india?"],
  ["what are the best ways to use social media to promote my amazon india business?"],
  ["how can i leverage data analytics to improve my amazon india performance?"],
  ["what are some common challenges faced by amazon india sellers, and how can i overcome them?"],
  ["what resources are available to help me learn more about selling on amazon india?"],
  ["is there a difference between selling private label and other brands on amazon india?"],
  ["what are the best practices for product packaging and shipping for amazon india?"],
  ["how can i manage returns and refunds efficiently on amazon india?"],
  ["what are the tax implications of selling on amazon india?"],
  ["how can i protect my intellectual property when selling on amazon india?"],
  ["what are the future trends and opportunities for amazon india sellers?"],
  ["how can i stay updated on the latest amazon india policies and updates?"],
  ["how can i measure the success of my amazon india business and track my progress?"],
  ["what are the different types of flipkart seller accounts?"],
  ["what documents do i need to open a flipkart seller account"],
  ["what are the fees associated with selling on flipkart?"],
  ["what products can i sell on flipkart?"],
  ["how do i list my products on flipkart?"],
  ["how do i ship my products to flipkart customers?"],
  ["how can i promote my products on flipkart?"],
  ["how do i provide customer service on flipkart?"],
  ["what happens if i receive negative feedback?"],
  ["how can i grow my flipkart seller business?"],
  ["what are the benefits of selling on flipkart compared to other platforms?"],
  ["how can i ensure my product listings are optimized for flipkart search terms?"],
  ["what are the best practices for product pricing on flipkart?"],
  ["how can i manage my inventory effectively to avoid stockouts or overstocking?"],
  ["what are the different ways to offer customer support on flipkart?"],
  ["how can i use flipkart's promotional tools and events to boost sales?"],
  ["what are the legal and regulatory considerations for selling specific product categories on flipkart?"],
  ["how can i build a positive brand reputation on flipkart?"],
  ["what are the best ways to use social media to promote my flipkart business?"],
  ["how can i leverage data analytics to improve my flipkart performance"]

]

// Response

const replies = [
  ["Hello!", "Hi!", "Hey!", "Hi there!","Howdy"],
  ["Fine... how are you?", "Pretty well, how are you?", "Fantastic, how are you?"],
  ["Nothing much", "About to go to sleep", "Can you guess?", "I don't know actually"],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],
  ["The one true God, JavaScript"],
  ["I am nameless", "I don't have a name"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["Bye", "Goodbye", "See you later"],
  ["Sushi", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok","I understand","What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!","Good one!"],
  ["E-commerce, or electronic commerce, refers to the buying and selling of goods and services over the internet.", "E-commerce involves online transactions and business activities conducted electronically."],
  ["To start selling online, you can begin by choosing a niche, creating an e-commerce website, setting up secure payment methods, and implementing digital marketing strategies.", "The steps to commence online selling include market research, product selection, platform setup, and promotion."],
  ["Key components of a successful e-commerce website include a user-friendly interface, high-quality product images, detailed product descriptions, easy navigation, and secure checkout processes.", "Crucial elements for a successful online store include mobile responsiveness, clear call-to-action buttons, and an efficient inventory management system."],
  ["Digital marketing is highly important in e-commerce as it helps increase brand visibility, drive traffic, and convert leads into customers through various online channels such as social media, email, and search engines.", "The role of digital marketing in online selling is significant for reaching a wider audience and staying competitive in the digital landscape."],
  ["Common challenges in e-commerce include fierce competition, cybersecurity concerns, logistics and shipping issues, and ensuring a positive user experience.", "Challenges faced by online sellers encompass adapting to market changes, handling customer complaints, and managing inventory effectively."],
  ["To optimize product listings, focus on creating compelling product descriptions, using high-quality images, incorporating relevant keywords, and highlighting unique selling points.", "Strategies for effective product listings involve providing detailed specifications, offering product bundles, and using customer reviews to build trust."],
  ["Offer secure payment options such as credit cards, digital wallets, and online payment gateways. Ensure a seamless and secure payment processing experience for customers.", "Best practices for online payment processing include using SSL certificates, encrypting sensitive data, and offering multiple payment options to cater to diverse customer preferences."],
  ["Improving customer satisfaction in e-commerce can be achieved by providing responsive customer support, offering hassle-free returns, personalizing the shopping experience, and requesting feedback for continuous improvement.", "Strategies to enhance customer experience online involve providing real-time assistance, streamlining the checkout process, and implementing a customer loyalty program."],
  ["Dropshipping is a retail fulfillment method where a store doesn't keep the products it sells in stock. Instead, when a store sells a product, it purchases the item from a third party and has it shipped directly to the customer.", "Dropshipping is a business model that allows entrepreneurs to sell products without dealing with inventory management and order fulfillment."],
  ["Emerging trends in e-commerce include the rise of mobile shopping, augmented reality for online product visualization, voice commerce, and sustainability-driven consumer preferences.", "The future landscape of e-commerce is shaped by technological advancements, changing consumer behaviors, and a focus on creating seamless and personalized online shopping experiences."],
  ["To handle returns and refunds, establish clear policies, communicate them to customers, and streamline the return process. Provide a hassle-free experience to build trust and customer satisfaction.", "Managing returns involves setting up a returns portal, ensuring transparency in refund policies, and promptly addressing customer inquiries regarding returns and refunds."],
  ["Customer reviews play a crucial role in building trust and credibility for your online business. Positive reviews can influence purchasing decisions and contribute to a positive brand image.", "The importance of customer feedback in online selling lies in its ability to provide valuable insights, build credibility, and influence the purchasing decisions of potential customers."],
  ["Social media plays a vital role in e-commerce marketing by providing a platform for brand promotion, customer engagement, and targeted advertising. Utilize social media channels to connect with your audience and showcase your products.", "Leveraging social media for online marketing involves creating engaging content, running targeted ads, and building a community around your brand to increase brand awareness and drive traffic to your e-commerce site."],
  ["SEO, or search engine optimization, is crucial for e-commerce as it helps improve the visibility of your website on search engine results. Optimize your product pages, use relevant keywords, and focus on creating high-quality content to rank higher in search engine listings.", "Search engine optimization in e-commerce involves optimizing product listings, creating SEO-friendly URLs, and regularly updating website content to improve search engine rankings and attract organic traffic."],
  ["Considerations for setting shipping policies in e-commerce include determining shipping rates, offering multiple shipping options, and clearly communicating shipping times. Providing transparent shipping policies builds trust with customers.", "Establishing effective shipping policies for your online store involves considering factors such as shipping costs, delivery times, and potential international shipping options based on your target audience and products."],
  ["To protect customer data, implement secure payment gateways, use encryption technologies, and comply with data protection regulations. Building trust in the security of online transactions is crucial for customer confidence and satisfaction.", "Implementing data protection practices in e-commerce involves securing customer information, regularly updating security measures, and adhering to data protection laws to safeguard sensitive information and maintain customer trust."],
  ["AI plays a crucial role in personalizing the e-commerce shopping experience by analyzing user behavior, predicting preferences, and offering tailored product recommendations. Incorporate AI algorithms to provide a personalized and engaging shopping journey for your customers.", "AI enhances personalization in e-commerce by utilizing machine learning algorithms to analyze customer behavior, predict preferences, and offer personalized product recommendations, ultimately improving the overall shopping experience."],
  ["The advantages of selling on online marketplaces include increased visibility, access to a broader customer base, and the convenience of leveraging an established platform. Listing products on multiple online marketplaces can enhance your reach and sales potential.", "Benefits of selling on online marketplaces involve reaching a wider audience, leveraging the marketplace's existing customer base, and gaining access to built-in marketing and logistics services for streamlined operations."],
  ["Building brand loyalty in e-commerce requires consistent branding, exceptional customer service, and loyalty programs. Offer incentives, personalized communication, and exclusive deals to encourage repeat purchases and foster loyalty.", "Strategies to enhance brand loyalty in e-commerce involve creating a memorable brand identity, delivering exceptional customer experiences, and implementing loyalty programs to reward and retain customers."],
  ["Effective strategies for reducing cart abandonment in e-commerce include optimizing the checkout process, offering transparent pricing, and implementing cart recovery emails. Addressing concerns and providing incentives can help decrease cart abandonment rates.", "Minimizing cart abandonment involves streamlining the checkout process, displaying clear shipping costs, and implementing cart recovery strategies, such as sending reminder emails and offering discounts to encourage customers to complete their purchases."],
  [
    "individual (free, 100 units/month limit), professional (₹1,200/year, unlocks features)",
  ],
  [
    "pan card, bank account, cancelled cheque, gst registration (optional), business license (optional)",
  ],
  ["professional account fee, selling fees, fba fees (optional), referral fees (5-15%)"],
  ["most products allowed, check prohibited and restricted lists"],
  ["through seller central, provide details like title, description, images, price, shipping"],
  ["handle yourself (fbm) or use fulfillment by amazon (fba)"],
  ["sponsored products, sponsored brands, off-platform marketing, seo optimization"],
  ["respond promptly and professionally through seller central, maintain high rating"],
  ["address issue promptly, negative feedback can impact sales, strive for high rating"],
  ["analyze sales data, customer feedback, experiment with products, pricing, marketing, adapt to market"],
  [
    "large customer base, established trust, advanced marketing tools, e-commerce infrastructure",
  ],
  ["use relevant keywords, translate descriptions, localize images"],
  ["competitive research, consider discounts, factor in logistics costs"],
  ["track levels, use forecasting tools, set reorder points, manage FBA"],
  ["seller central messaging, phone support, email, chatbots, social media"],
  ["flash deals, seasonal promotions, prime day, sponsored ads, product bundles"],
  ["check category guidelines, obtain necessary licenses and certifications"],
  ["responsive service, high-quality products, positive feedback, engaging brand story"],
  ["targeted ads, share product stories, engage with local communities, use relevant hashtags"],
  ["track sales data, monitor reviews, analyze conversion rates, optimize listings based on insights"],
  ["competition, logistics challenges, counterfeits, managing returns, adapting to local preferences"],
  ["seller central resources, online communities, seller forums, webinars, training programs"],
  ["higher margins, brand control, potential for loyalty, but increased marketing and branding efforts"],
  ["durable packaging, weatherproof materials, consider size/weight restrictions, clear labeling, efficient shipping partners"],
  ["streamlined process, clear policy, prompt communication, efficient inventory management"],
  ["consult with a tax advisor, understand GST rules, calculate and file taxes accurately"],
  ["register trademarks, secure copyrights, avoid infringing materials, be vigilant about counterfeiting"],
  ["growing mobile commerce, personalization opportunities, voice shopping, rural market expansion, niche category potential"],
  ["subscribe to seller central news, follow amazon india social media, attend seller events, join online communities"],
  ["track key metrics like sales, conversion rates, average order value, customer feedback, return rates, compare against goals and benchmarks"],
  [
    "individual (free, limited sales), wholesale (higher limits, gst required), brand (highest limits, established brands)",
  ],
  [
    "pan card, gst registration (optional), bank account, cancelled cheque, business license (certain categories)",
  ],
  ["listing fees (per ad), commission fees (percentage of sale), payment gateway fees, logistics fees (if not fpk)"],
  ["most products allowed, check prohibited and restricted lists"],
  ["through seller hub, provide details like title, description, images, price, specifications"],
  ["handle yourself (fms) or use flipkart fulfillment program (fpk)"],
  ["flipkart ads, brand story, flash sales, supercoin days, product listings optimization"],
  ["seller hub messaging, phone support, email, chatbots, social media channels"],
  ["address promptly, offer resolutions, negative feedback can impact ranking"],
  ["analyze data, optimize listings, run promotions, expand product range, offer excellent customer service"],
  ["large customer base, established brand, localized platform, flipkart ads reach"],
  ["use relevant keywords in title and description, translate for local languages, localize images"],
  ["competitive research, consider discounts and promotions, factor in logistics costs"],
  ["track inventory levels, utilize forecasting tools, set reorder points, manage fpk efficiently"],
  ["seller hub messaging, phone support, email, chatbots, social media channels"],
  ["flash sales, supercoin days, sponsored ads, product bundles, brand story campaigns"],
  ["check specific category guidelines, obtain necessary licenses and certifications"],
  ["responsive customer service, high-quality products, positive feedback, engaging brand story"],
  ["run targeted ads, share product stories, engage with relevant communities, participate in flipkart's social media initiatives"],
  ["track sales data, monitor reviews, analyze conversion rates, optimize listings and marketing based on insights"]
]

// Random for any other user input

const alternative = [
  "Same",
  "Go on...",
  "Bro...",
  "Try again",
  "I'm listening...",
  "I don't understand :/"
]

// Whatever else you want :)

const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]